$(document).ready(function(){
  $('.slider').slick({
    arrows:false,
    dots:true,
    speed:1000,
    Infinity:true,
    autoplay:true,
    autoplayspeed:10000,
    pauseOnFocuse:true,
    pauseOnHover:true,
    pauseOnDotsHover:true,
    waitForAnimate:false,
    slideerToShow:1
  });
})